// Generated by CoffeeScript 1.3.3
/*
Copyright (c) 2012 [DeftJS Framework Contributors](http://deftjs.org)
Open source under the [MIT License](http://en.wikipedia.org/wiki/MIT_License).
*/

Carcasse.define('Carcasse.promise.Deferred', {
  alternateClassName: ['Carcasse.Deferred'],
  constructor: function() {
    this.state = 'pending';
    this.progress = void 0;
    this.value = void 0;
    this.progressCallbacks = [];
    this.successCallbacks = [];
    this.failureCallbacks = [];
    this.cancelCallbacks = [];
    this.promise = Carcasse.create('Carcasse.Promise', this);
    return this;
  },
  /**
  	Returns a new {@link Carcasse.promise.Promise} with the specified callbacks registered to be called when this {@link Carcasse.promise.Deferred} is resolved, rejected, updated or cancelled.
  */

  then: function(callbacks) {
    var callback, cancelCallback, deferred, failureCallback, progressCallback, successCallback, wrapCallback, wrapProgressCallback, _i, _len, _ref;
    if (Carcasse.isObject(callbacks)) {
      successCallback = callbacks.success, failureCallback = callbacks.failure, progressCallback = callbacks.progress, cancelCallback = callbacks.cancel;
    } else {
      successCallback = arguments[0], failureCallback = arguments[1], progressCallback = arguments[2], cancelCallback = arguments[3];
    }
    _ref = [successCallback, failureCallback, progressCallback, cancelCallback];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      callback = _ref[_i];
      if (!(Carcasse.isFunction(callback) || callback === null || callback === void 0)) {
        Carcasse.Error.raise({
          msg: 'Error while configuring callback: a non-function specified.'
        });
      }
    }
    deferred = Carcasse.create('Carcasse.promise.Deferred');
    wrapCallback = function(callback, action) {
      return function(value) {
        var result;
        if (Carcasse.isFunction(callback)) {
          try {
            result = callback(value);
            if (result === void 0) {
              deferred[action](value);
            } else if (result instanceof Carcasse.ClassManager.get('Carcasse.promise.Promise') || result instanceof Carcasse.ClassManager.get('Carcasse.promise.Deferred')) {
              result.then(Carcasse.bind(deferred.resolve, deferred), Carcasse.bind(deferred.reject, deferred), Carcasse.bind(deferred.update, deferred), Carcasse.bind(deferred.cancel, deferred));
            } else {
              deferred.resolve(result);
            }
          } catch (error) {
            deferred.reject(error);
          }
        } else {
          deferred[action](value);
        }
      };
    };
    this.register(wrapCallback(successCallback, 'resolve'), this.successCallbacks, 'resolved', this.value);
    this.register(wrapCallback(failureCallback, 'reject'), this.failureCallbacks, 'rejected', this.value);
    this.register(wrapCallback(cancelCallback, 'cancel'), this.cancelCallbacks, 'cancelled', this.value);
    wrapProgressCallback = function(callback) {
      return function(value) {
        var result;
        if (Carcasse.isFunction(callback)) {
          result = callback(value);
          if (result === void 0) {
            deferred.update(value);
          } else {
            deferred.update(result);
          }
        } else {
          deferred.update(value);
        }
      };
    };
    this.register(wrapProgressCallback(progressCallback), this.progressCallbacks, 'pending', this.progress);
    return deferred.getPromise();
  },
  /**
  	Returns a new {@link Carcasse.promise.Promise} with the specified callbacks registered to be called when this {@link Carcasse.promise.Deferred} is either resolved, rejected, or cancelled.
  */

  always: function(alwaysCallback) {
    return this.then({
      success: alwaysCallback,
      failure: alwaysCallback,
      cancel: alwaysCallback
    });
  },
  /**
  	Update progress for this {@link Carcasse.promise.Deferred} and notify relevant callbacks.
  */

  update: function(progress) {
    if (this.state === 'pending') {
      this.progress = progress;
      this.notify(this.progressCallbacks, progress);
    } else {
      Carcasse.Error.raise({
        msg: 'Error: this Deferred has already been completed and cannot be modified.'
      });
    }
  },
  /**
  	Resolve this {@link Carcasse.promise.Deferred} and notify relevant callbacks.
  */

  resolve: function(value) {
    this.complete('resolved', value, this.successCallbacks);
  },
  /**
  	Reject this {@link Carcasse.promise.Deferred} and notify relevant callbacks.
  */

  reject: function(error) {
    this.complete('rejected', error, this.failureCallbacks);
  },
  /**
  	Cancel this {@link Carcasse.promise.Deferred} and notify relevant callbacks.
  */

  cancel: function(reason) {
    this.complete('cancelled', reason, this.cancelCallbacks);
  },
  /**
  	Get this {@link Carcasse.promise.Deferred}'s associated {@link Carcasse.promise.Promise}.
  */

  getPromise: function() {
    return this.promise;
  },
  /**
  	Get this {@link Carcasse.promise.Deferred}'s current state.
  */

  getState: function() {
    return this.state;
  },
  /**
  	Register a callback for this {@link Carcasse.promise.Deferred} for the specified callbacks and state, immediately notifying with the specified value (if applicable).
  	@private
  */

  register: function(callback, callbacks, state, value) {
    if (Carcasse.isFunction(callback)) {
      if (this.state === 'pending') {
        callbacks.push(callback);
        if (this.state === state && value !== void 0) {
          this.notify([callback], value);
        }
      } else {
        if (this.state === state) {
          this.notify([callback], value);
        }
      }
    }
  },
  /**
  	Complete this {@link Carcasse.promise.Deferred} with the specified state and value.
  	@private
  */

  complete: function(state, value, callbacks) {
    if (this.state === 'pending') {
      this.state = state;
      this.value = value;
      this.notify(callbacks, value);
      this.releaseCallbacks();
    } else {
      Carcasse.Error.raise({
        msg: 'Error: this Deferred has already been completed and cannot be modified.'
      });
    }
  },
  /**
  	Notify the specified callbacks with the specified value.
  	@private
  */

  notify: function(callbacks, value) {
    var callback, _i, _len;
    for (_i = 0, _len = callbacks.length; _i < _len; _i++) {
      callback = callbacks[_i];
      callback(value);
    }
  },
  /**
  	Release references to all callbacks registered with this {@link Carcasse.promise.Deferred}.
  	@private
  */

  releaseCallbacks: function() {
    this.progressCallbacks = null;
    this.successCallbacks = null;
    this.failureCallbacks = null;
    this.cancelCallbacks = null;
  }
});
